### ISSUE TITLE
DLNA Play Media: status: 500, upnp error: 716

### ISSUE THREAD

**Issue by AquaMCU** [Chouffy/home_assistant_libratone_zipp#5]
Hi.

I tried the integration and it works ... But when I do not play media for a while, the player does not start i hear a "BING" and in the logs, I get the below mentioned error message. What can I do?

Regads Oliver

2023-09-18 06:38:23.083 ERROR (MainThread) [homeassistant.components.dlna_dmr] Error during call async_play_media: UpnpActionResponseError('Error during async_call(), status: 500, upnp error: 716 (resource is not found)')

**Comment by Chouffy** [comment]
Hey @AquaMCU 

I see that you're using the UPNP/DLNA component here to trigger a media play.
This is an integration provided by Home Assistant: https://www.home-assistant.io/integrations/dlna_dmr/

So unfortunately not a lot that I can do for you … 😔
I've noticed that DLNA integration by Libratone has been not great, but I don't use it personally
